# Model arguments
# model_name_or_path: alignment-handbook/zephyr-7b-sft-full
# model_revision: ac6e600eefcce74f5e8bae1035d4f66019e93190
model_name_or_path: UCLA-AGI/zephyr-7b-sft-full-SPIN-iter0 # Change this to outputs/iter0-ckpt if trained by finetune.sh

# Data training arguments
dataset_mixer:
  #HuggingFaceH4/ultrafeedback_binarized: 1.0
  UCLA-AGI/SPIN_iter1: 1.0
dataset_splits:
- train
- test
preprocessing_num_workers: 10

# Trainer arguments
bf16: true
beta: 0.1
do_eval: false
evaluation_strategy: "no"
eval_steps: 100
gradient_accumulation_steps: 16
gradient_checkpointing: false
hub_model_id: zephyr-7b-spin
learning_rate: 5.0e-5
log_level: info
logging_steps: 5
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: /data/tir/projects/tir7/user_data/srijithr/spin_outputs
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
push_to_hub: false
save_strategy: "epoch"
save_total_limit: null
seed: 42
warmup_ratio: 0.1

run_name: SPIN_iter1_L40
use_peft : true
report_to: wandb
# lora_target_modules: 'k_proj q_proj v_proj'
# lora_modules_to_save:
# - q_proj
# - k_proj
# - v_proj
lora_target_modules:
- q_proj
- k_proj
- v_proj